version: '3'

networks:
  docker_red:
    driver: bridge

services:
  personams:
    build: ./persona-ms
    networks:
      - docker_red
    ports:
      - 9080:8080

  cuentams:
    build: ./cuenta-ms
    networks:
      - docker_red
    ports:
      - 9081:8081

  postgresdb:
    build: ./database
    networks:
      - docker_red
    ports:
      - 54320:5432

