springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.cllaque.personams
  pathsToMatch: /**

server:
  port: 8080

spring:
  application:
    name: personams

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/devsujava
    username: devsu
    password: devsu

  cloud.stream:
    defaultBinder: rabbit
    default.contentType: application/json
    bindings.crearClienteMessageProcessor-in-0:
      destination: clientes

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5


logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

---
spring:
  config.activate.on-profile: docker
  r2dbc:
    url: r2dbc:postgresql://personadb:5432/personadb
    username: user
    password: pass

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka.client.serviceUrl.defaultZone: http://eurekaserver:8761/eureka/
