server:
  port: 8082
spring:
  application:
    name: movimientoms

  r2dbc:
    url: r2dbc:h2:mem:///devsujava?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: 

logging:
  level:
    org.springframework.r2dbc: DEBUG

cuentams:
  url: http://localhost:8081
