server.port: 8080
spring:
  application.name: edgeserver
  cloud:
    gateway:
      routes:
        - id: compositems
          predicates:
            - Path=/composite/**
          filters:
            - RewritePath=/composite/?(?<segment>.*), /$\{segment}
          uri: lb://compositems #Destination
        - id: eureka-api
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}
          uri: http://${app.eurekaserver}:8761
        - id: eureka-web-start
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
          uri: http://${app.eurekaserver}:8761
        - id: eureka-web-other
          predicates:
            - Path=/eureka/**
          uri: http://${app.eurekaserver}:8761

app:
  eurekaserver: localhost

eureka:
  client:
    serviceUrl.defaultZone: http://${app.eurekaserver}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring.config.activate.on-profile: docker
app.eurekaserver: eurekaserver

