server:
  port: 8080

spring:
  application:
    name: compositems

  cloud.stream:
    defaultBinder: rabbit
    default.contentType: application/json
    bindings:
      clientes-out-0:
        destination: clientes
        producer:
          required-groups: auditGroup

      cuentas-out-0:
        destination: cuentas
        producer:
          required-groups: auditGroup

      movimientos-out-0:
        destination: movimientos
        producer:
          required-groups: auditGroup

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

eurekaurl:
  personams: http://personams:8080
  cuentams: http://cuentams:8080
  movimientoms: http://movimientoms:8080

ms:
  url:
    persona: http://localhost:8080
    cuenta: http://localhost:8080
    movimiento: http://localhost:8080

logging:
  level:
    root: INFO

management.health.circuitbreakers.enabled: true

resilience4j:
  timelimiter:
    instances:
      cliente:
        timeOutDuration: 2s

  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      cliente:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management.endpoint.health.show-details: always
---
spring:
  config.activate.on-profile: docker

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
ms:
  url:
    persona: http://personaservice:8080
    cuenta: http://cuentaservice:8080
    movimiento: http://movimientoservice:8080

eureka:
  client:
    serviceUrl.defaultZone: http://eurekaserver:8761/eureka/
