server:
  port: 8080
spring:
  application:
    name: cuentams

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/devsujava
    username: devsu
    password: devsu

  cloud.stream:
    defaultBinder: rabbit
    default.contentType: application/json
    bindings.crearCuentaMessageProcessor-in-0.destination: cuentas

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

eurekaurl:
  personams: http://personams:8080
  movimientoms: http://movimientoms:8080

personams:
  url: http://localhost:8080
movimientoms:
  url: http://localhost:8080

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
---
spring:
  config.activate.on-profile: docker
  r2dbc:
    url: r2dbc:postgresql://cuentadb:5432/cuentadb
    username: user
    password: pass

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka.client.serviceUrl.defaultZone: http://eurekaserver:8761/eureka/

personams:
  url: http://personaservice:8080
movimientoms:
  url: http://movimientoservice:8080
